name: build-image

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - uses: docker/setup-buildx-action@v3

            - uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - uses: docker/metadata-action@v5
              id: meta
              with:
                  images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/basicvsrpp
                  tags: |
                      type=ref,event=branch
                      type=ref,event=tag
                      type=raw,value=cu124-torch260-ubuntu2204

            - uses: docker/build-push-action@v6
              with:
                  context: .
                  file: docker/Dockerfile.runpod-bsvrpp
                  platforms: linux/amd64
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      BASE_IMAGE=runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04
                      BSVRPP_REPO=https://github.com/0xmrwn/basicvsrpp
                      BSVRPP_REF=master
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
